# Generated by Django 6.0.7 on 2026-07-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiket Adı')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İşlem Başlığı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Gelir'), ('EXPENSE', 'Gider')], max_length=10, verbose_name='İşlem Türü')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('currency', models.CharField(default='TRY', max_length=10, verbose_name='Doviz Cinsi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, to='tracker.tag', verbose_name='Etiketler')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
            },
        ),
    ]
