# Generated by Django 6.0.7 on 2026-07-30 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Kategori Bütçe Limiti', 'verbose_name_plural': 'Kategori Bütçe Limitleri'},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'category')},
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aylık Limit (TRY)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
