# Generated by Django 6.0.7 on 2026-07-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlimit',
            options={'verbose_name': 'Kategori Bütçe Limiti', 'verbose_name_plural': 'Kategori Bütçe Limitleri'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('user', 'category')},
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='İşlem Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Gelir'), ('EXPENSE', 'Gider')], max_length=10, verbose_name='Tür')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('interval', models.CharField(choices=[('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık'), ('MONTHLY', 'Aylık'), ('YEARLY', 'Yıllık')], default='MONTHLY', max_length=10, verbose_name='Tekrar Sıklığı')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('next_date', models.DateField(verbose_name='Sonraki İşlem Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Tekrarlayan İşlem',
                'verbose_name_plural': 'Tekrarlayan İşlemler',
            },
        ),
    ]
