# Generated by Django 6.0.7 on 2026-08-01 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_budgetlimit_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlimit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aylık Bütçe Limiti (TRY)'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (TRY)'), ('USD', 'Amerikan Doları (USD)'), ('EUR', 'Euro (EUR)')], default='TRY', max_length=3, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.CharField(choices=[('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık'), ('MONTHLY', 'Aylık'), ('YEARLY', 'Yıllık')], max_length=10, verbose_name='Tekrarlama Sıklığı'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='title',
            field=models.CharField(max_length=150, verbose_name='İşlem Başlığı'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Gelir'), ('EXPENSE', 'Gider')], max_length=10, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (TRY)'), ('USD', 'Amerikan Doları (USD)'), ('EUR', 'Euro (EUR)')], default='TRY', max_length=3, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=150, verbose_name='İşlem Başlığı'),
        ),
    ]
