# Generated by Django 6.0.7 on 2026-08-01 16:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_budgetlimit_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Grup Adı')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('members', models.ManyToManyField(related_name='expense_groups', to=settings.AUTH_USER_MODEL, verbose_name='Grup Üyeleri')),
            ],
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Harcama Açıklaması')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası (TRY)'), ('USD', 'Amerikan Doları (USD)'), ('EUR', 'Euro (EUR)')], default='TRY', max_length=3, verbose_name='Döviz Cinsi')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Tarih')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.expensegroup', verbose_name='Harcama Grubu')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Ödeyen Kişi')),
            ],
        ),
    ]
