# Generated by Django 6.0.7 on 2026-08-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_categorylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50, verbose_name='Kart Adı (Örn: Bonus, Axess)')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kart Limiti')),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dönem Borcu')),
                ('due_date', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Asgari Ödeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
