# Generated by Django 6.0.7 on 2026-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='priority',
            field=models.CharField(choices=[('RED', '🔴 Zorunlu'), ('YELLOW', '🟡 İhtiyaç'), ('GREEN', '🟢 Keyfi')], default='YELLOW', max_length=10, verbose_name='Harcama Önceliği'),
        ),
    ]
